# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\rppl.llm.proto\"U\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x19\n\x11generation_length\x18\x03 \x01(\r\x12\x0e\n\x06prompt\x18\x04 \x01(\t\"5\n\x0e\x42\x61tchedRequest\x12#\n\x03req\x18\x01 \x03(\x0b\x32\x16.ppl.llm.proto.Request\"P\n\x08Response\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.ppl.llm.proto.Status\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x11\n\tgenerated\x18\x03 \x01(\t*2\n\x06Status\x12\x0e\n\nPROCESSING\x10\x00\x12\x0c\n\x08\x46INISHED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x32V\n\nLLMService\x12H\n\nGeneration\x12\x1d.ppl.llm.proto.BatchedRequest\x1a\x17.ppl.llm.proto.Response\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=252
  _globals['_STATUS']._serialized_end=302
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=113
  _globals['_BATCHEDREQUEST']._serialized_start=115
  _globals['_BATCHEDREQUEST']._serialized_end=168
  _globals['_RESPONSE']._serialized_start=170
  _globals['_RESPONSE']._serialized_end=250
  _globals['_LLMSERVICE']._serialized_start=304
  _globals['_LLMSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
