# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\rppl.llm.proto\"m\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x19\n\x11generation_length\x18\x03 \x01(\r\x12\x0e\n\x06prompt\x18\x04 \x01(\x0c\x12\x16\n\x0e\x65\x61rly_stopping\x18\x05 \x01(\x08\"5\n\x0e\x42\x61tchedRequest\x12#\n\x03req\x18\x01 \x03(\x0b\x32\x16.ppl.llm.proto.Request\"P\n\x08Response\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.ppl.llm.proto.Status\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x11\n\tgenerated\x18\x03 \x01(\x0c\"7\n\x0f\x42\x61tchedResponse\x12$\n\x03rsp\x18\x01 \x03(\x0b\x32\x17.ppl.llm.proto.Response*2\n\x06Status\x12\x0e\n\nPROCESSING\x10\x00\x12\x0c\n\x08\x46INISHED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x32]\n\nLLMService\x12O\n\nGeneration\x12\x1d.ppl.llm.proto.BatchedRequest\x1a\x1e.ppl.llm.proto.BatchedResponse\"\x00\x30\x01\x62\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
PROCESSING = 0
FINISHED = 1
FAILED = 2


_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_BATCHEDREQUEST = DESCRIPTOR.message_types_by_name['BatchedRequest']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_BATCHEDRESPONSE = DESCRIPTOR.message_types_by_name['BatchedResponse']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'llm_pb2'
  # @@protoc_insertion_point(class_scope:ppl.llm.proto.Request)
  })
_sym_db.RegisterMessage(Request)

BatchedRequest = _reflection.GeneratedProtocolMessageType('BatchedRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHEDREQUEST,
  '__module__' : 'llm_pb2'
  # @@protoc_insertion_point(class_scope:ppl.llm.proto.BatchedRequest)
  })
_sym_db.RegisterMessage(BatchedRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'llm_pb2'
  # @@protoc_insertion_point(class_scope:ppl.llm.proto.Response)
  })
_sym_db.RegisterMessage(Response)

BatchedResponse = _reflection.GeneratedProtocolMessageType('BatchedResponse', (_message.Message,), {
  'DESCRIPTOR' : _BATCHEDRESPONSE,
  '__module__' : 'llm_pb2'
  # @@protoc_insertion_point(class_scope:ppl.llm.proto.BatchedResponse)
  })
_sym_db.RegisterMessage(BatchedResponse)

_LLMSERVICE = DESCRIPTOR.services_by_name['LLMService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=333
  _STATUS._serialized_end=383
  _REQUEST._serialized_start=28
  _REQUEST._serialized_end=137
  _BATCHEDREQUEST._serialized_start=139
  _BATCHEDREQUEST._serialized_end=192
  _RESPONSE._serialized_start=194
  _RESPONSE._serialized_end=274
  _BATCHEDRESPONSE._serialized_start=276
  _BATCHEDRESPONSE._serialized_end=331
  _LLMSERVICE._serialized_start=385
  _LLMSERVICE._serialized_end=478
# @@protoc_insertion_point(module_scope)
