# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import os
import sys

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../../..")
import Code.src.http.llm_pb2 as llm__pb2
# import llm_pb2 as llm__pb2


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generation = channel.unary_stream(
                '/ppl.llm.proto.LLMService/Generation',
                request_serializer=llm__pb2.BatchedRequest.SerializeToString,
                response_deserializer=llm__pb2.BatchedResponse.FromString,
                )


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generation': grpc.unary_stream_rpc_method_handler(
                    servicer.Generation,
                    request_deserializer=llm__pb2.BatchedRequest.FromString,
                    response_serializer=llm__pb2.BatchedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ppl.llm.proto.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ppl.llm.proto.LLMService/Generation',
            llm__pb2.BatchedRequest.SerializeToString,
            llm__pb2.BatchedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
