- name: "Llama2-7B"
  model_path: "/mxstorage/pde_ai/models/llm/Llama/Llama-2-7b-hf"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


# -name: "Llama2_7b_sql_lora"


- name: "DeepSeek-R1-Distill-Llama-70B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Llama-70B/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "DeepSeek-R1-Distill-Llama-8B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Llama-8B/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-Next-80B-A3B-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Next-80B-A3B-Instruct.w8a8/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "GLM4.5-Air-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/ChatGLM/GLM-4.5-Air.w8a8/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "ChatGLM3-6B"
  model_path: "/mxstorage/pde_ai/models/llm/ChatGLM/chatglm3-6b/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Baichuan2-7B-Chat"
  model_path: "/mxstorage/pde_ai/models/llm/Baichuan/Baichuan2-7B-Chat/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-8B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-8B/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-14B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-14B/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-30B-A3B-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-30B-A3B.w8a8/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-32B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-32B/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-30B-A3B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-30B-A3B/"
  serve_config:
    tp: 2
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-VL-4B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-4B-Instruct/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - single-image
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-VL-8B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-8B-Instruct/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - single-image
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-VL-30B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-30B-A3B-Instruct/"
  serve_config:
    tp: 2
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - single-image
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen3-Omni-30B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Omni-30B-A3B-Instruct/"
  serve_config:
    tp: 2
    dp: 1
    pp: 1
    extra_args:
      --dtype: "bfloat16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - single-image
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen2.5-72B-Instruct-GPTQ-Int4"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2___5-72B-Instruct-GPTQ-Int4/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen2.5-72B-Instruct-AWQ"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2___5-72B-Instruct-AWQ/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "DeepSeek-R1-Distill-Qwen-7B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-7B/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "DeepSeek-R1-Distill-Qwen-14B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-14B/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "DeepSeek-R1-Distill-Qwen-32B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-32B/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_mainstream.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Mixtral-8x7B-V0.1"
  model_path: "/mxstorage/pde_ai/models/llm/Mistral/Mixtral-8x7B-v0.1/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "GLM4-9B-Chat"
  model_path: "/mxstorage/pde_ai/models/llm/ChatGLM/glm-4-9b-chat/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "QwQ-32B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/QwQ-32B/"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen2-72B-Instruct-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/W8A8/Qwen2-72B-Instruct-quantized___w8a8"
  serve_config:
    tp: 2
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Mixtral-8x22B-V0.1-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/W8A8/Mixtral-8x22B-Instruct-v0.1-INT8-Dynamic"
  serve_config:
    tp: 4
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.9
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Qwen2.5-14B-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/W8A8/Qwen2.5-14B-Instruct-W8A8-Dynamic-Per-Token"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:


- name: "Mistral-Nemo-12B"
  model_path: "/mxstorage/pde_ai/models/llm/Mistral/Mistral-Nemo-Instruct-2407/"
  serve_config:
    tp: 1
    dp: 1
    pp: 1
    extra_args:
      --dtype: "float16"
      --gpu-memory-utilization: 0.95
  infer_type:
    - text-only
  benchmark:
    bench_param: "configs/bench_params/bench_common.json"
    ignore_eos: true
    sweep_num_runs: 1
  extra_env:

